### PR TITLE
Desktop changes

### PR DESCRIPTION
**Pull request by jonmost**
trying to undue last change

### CODE REVIEW

**Comment by jonmost** [comment]
trying to fix "Do it" banner link

**Comment by dfcoffin** [comment]
Did you mean to update the Green Button GitHub repository?

**Comment by dfcoffin** [comment]
Closing this pull request as it appears to have been issued in error.  These changes would re-purpose the Green Button repository to function as the US Digital Service website.  The individual who issued this pull request appears to have forked the Green Button repository to create the US Digital Service website, but has maintained using the Green Button repository as the master.  A new GitHub repository needs to be created and the Green Button repository dropped as the master Git repository to prevent master repository updates from affecting the Green Button repository.

**Comment by jonmost** [comment]
No it was a mistake



Sent with Good (www.good.com)


-----Original Message-----

**Pull request closed without merging**
